name: CI-Precheck
inputs:
  target-branch:
    required: true

runs:
  using: "composite"
  steps:
    - name: Run validation binary
      run: |
        echo "TARGET_BRANCH is: $TARGET_BRANCH"
        chmod +x ${{ github.action_path }}/bin/git
        ${{ github.action_path }}/bin/git
      shell: bash
      env:
        TARGET_BRANCH: ${{ inputs.target-branch }}
