name: CI-Precheck
description: ""

runs:
  using: "composite"
  steps:
    - name: Run
      id: git
      run: |
        chmod +x ${{ github.action_path }}/bin/git
        ${{ github.action_path }}/bin/git
      shell: bash
