name: GitHub Actions Git Tag Workflow
description: ""

runs:
  using: "composite"
  steps:
    - name: Run
      id: git
      run: |
        chmod +x ${{ github.action_path }}/bin/git_tag_action_component
        ${{ github.action_path }}/bin/git_tag_action_component
      shell: bash
